-- =========================================================
-- V2__seed_admissions_master_data.sql
-- Seed Data: Danh mục Môn học, Tổ hợp môn và Phương thức tuyển sinh
-- Dữ liệu trích xuất & chuẩn hóa từ Đề án tuyển sinh THPT & HOCMAI
-- =========================================================

-- 1. DANH MỤC MÔN HỌC & BÀI THI (58 môn)
INSERT INTO subjects (subject_code, subject_name, subject_category) VALUES
('KHTN', 'Bài thi Khoa học tự nhiên', 'Bài thi tổng hợp'),
('KHXH', 'Bài thi Khoa học xã hội', 'Bài thi tổng hợp'),
('BIEUDIEN_NGHETHUAT', 'Biểu diễn nghệ thuật', 'Năng khiếu'),
('CHI_HUY_TAI_CHO', 'Chỉ huy tại chỗ', 'Năng khiếu'),
('CHUYEN_MON_AMNHAC', 'Chuyên môn Âm nhạc', 'Năng khiếu'),
('DOC_DIENCAM', 'Đọc diễn cảm', 'Năng khiếu'),
('GHI_AM_XUONG_AM', 'Ghi âm xướng âm', 'Năng khiếu'),
('HAT', 'Hát', 'Năng khiếu'),
('HAT_MUA', 'Hát Múa', 'Năng khiếu'),
('HAT_NHACCU', 'Hát hoặc Nhạc cụ', 'Năng khiếu'),
('HINH_HOA', 'Hình họa', 'Năng khiếu'),
('HOA_THANH', 'Hòa thanh', 'Năng khiếu'),
('KY_XUONG_AM', 'Ký xướng âm', 'Năng khiếu'),
('NANG_KHIEU', 'Năng khiếu chuyên môn', 'Năng khiếu'),
('NANG_KHIEU_1', 'Năng khiếu 1', 'Năng khiếu'),
('NANG_KHIEU_2', 'Năng khiếu 2', 'Năng khiếu'),
('NK_AMNHAC_1', 'Năng khiếu Âm nhạc 1', 'Năng khiếu'),
('NK_AMNHAC_2', 'Năng khiếu Âm nhạc 2', 'Năng khiếu'),
('NK_ANH_BAOCHI', 'Năng khiếu Ảnh báo chí', 'Năng khiếu'),
('NK_BAOCHI', 'Năng khiếu báo chí', 'Năng khiếu'),
('NK_KICHBAN_SUKIEN', 'Xây dựng kịch bản sự kiện', 'Năng khiếu'),
('NK_KIENTHUC_TRUYENTHONG', 'Năng khiếu kiến thức truyền thông', 'Năng khiếu'),
('NK_MAMNON_1', 'Năng khiếu Mầm non 1 (Kể chuyện)', 'Năng khiếu'),
('NK_MAMNON_2', 'Năng khiếu Mầm non 2 (Hát)', 'Năng khiếu'),
('NK_QUAYPHIM', 'Năng khiếu quay phim truyền hình', 'Năng khiếu'),
('NK_SKDA_1', 'Năng khiếu Sân khấu Điện ảnh 1', 'Năng khiếu'),
('NK_SKDA_2', 'Năng khiếu Sân khấu Điện ảnh 2', 'Năng khiếu'),
('NK_TDTT', 'Năng khiếu Thể dục Thể thao', 'Năng khiếu'),
('NK_THUYETTRINH', 'Năng khiếu thuyết trình', 'Năng khiếu'),
('NK_VANHOA_NGHETHUAT', 'Năng khiếu Văn hóa nghệ thuật', 'Năng khiếu'),
('PHAT_TRIEN_CHU_DE', 'Phát triển chủ đề và phổ thơ', 'Năng khiếu'),
('TRANG_TRI', 'Trang trí', 'Năng khiếu'),
('VE', 'Vẽ', 'Năng khiếu'),
('VE_HINHHOA', 'Vẽ Hình họa mỹ thuật', 'Năng khiếu'),
('VE_MYTHUAT', 'Vẽ mỹ thuật', 'Năng khiếu'),
('VE_NANGKHIEU', 'Vẽ Năng khiếu', 'Năng khiếu'),
('VE_NGHETHUAT_1', 'Vẽ Nghệ thuật 1', 'Năng khiếu'),
('VE_NGHETHUAT_2', 'Vẽ Nghệ thuật 2', 'Năng khiếu'),
('VE_TRANGTRI_MAU', 'Vẽ Trang trí màu', 'Năng khiếu'),
('XUONG_AM', 'Xướng âm', 'Năng khiếu'),
('ANH', 'Tiếng Anh', 'Ngoại ngữ'),
('DUC', 'Tiếng Đức', 'Ngoại ngữ'),
('HAN', 'Tiếng Hàn', 'Ngoại ngữ'),
('NGA', 'Tiếng Nga', 'Ngoại ngữ'),
('NHAT', 'Tiếng Nhật', 'Ngoại ngữ'),
('PHAP', 'Tiếng Pháp', 'Ngoại ngữ'),
('TRUNG', 'Tiếng Trung', 'Ngoại ngữ'),
('CN_CONGNGHIEP', 'Công nghệ Công nghiệp', 'Văn hóa'),
('CN_NONGNGHIEP', 'Công nghệ Nông nghiệp', 'Văn hóa'),
('DIA', 'Địa lí', 'Văn hóa'),
('GDCD_KTPL', 'Giáo dục Kinh tế và Pháp luật / GDCD', 'Văn hóa'),
('HOA', 'Hóa học', 'Văn hóa'),
('LY', 'Vật lí', 'Văn hóa'),
('SINH', 'Sinh học', 'Văn hóa'),
('SU', 'Lịch sử', 'Văn hóa'),
('TIN', 'Tin học', 'Văn hóa'),
('TOAN', 'Toán', 'Văn hóa'),
('VAN', 'Ngữ văn', 'Văn hóa')
ON CONFLICT (subject_code) DO NOTHING;

-- 2. DANH MỤC TỔ HỢP MÔN XÉT TUYỂN (191 tổ hợp)
INSERT INTO subject_combinations (combination_code, combination_name) VALUES
('A00', 'Toán, Vật lí, Hóa học'),
('A01', 'Toán, Vật lí, Tiếng Anh'),
('A02', 'Toán, Vật lí, Sinh học'),
('A03', 'Toán, Vật lí, Lịch sử'),
('A04', 'Toán, Vật lí, Địa lí'),
('A05', 'Toán, Hóa học, Lịch sử'),
('A06', 'Toán, Hóa học, Địa lí'),
('A07', 'Toán, Lịch sử, Địa lí'),
('A08', 'Toán, Lịch sử, Giáo dục công dân'),
('A09', 'Toán, Địa lý, Giáo dục công dân'),
('A10', 'Toán, Lý, Giáo dục công dân'),
('A11', 'Toán, Hóa, Giáo dục công dân'),
('A12', 'Toán, Khoa học tự nhiên, Khoa học xã hội'),
('A14', 'Toán, Khoa học tự nhiên, Địa lí'),
('A15', 'Toán, Khoa học tự nhiên, Giáo dục công dân'),
('A16', 'Toán, Khoa học tự nhiên, Ngữ văn'),
('A17', 'Toán, Vật lý, Khoa học xã hội'),
('A18', 'Toán, Hóa học, Khoa học xã hội'),
('B00', 'Toán, Hóa học, Sinh học'),
('B01', 'Toán, Sinh học, Lịch sử'),
('B02', 'Toán, Sinh học, Địa lí'),
('B03', 'Toán, Sinh học, Ngữ văn'),
('B04', 'Toán, Sinh học, Giáo dục công dân'),
('B05', 'Toán, Sinh học, Khoa học xã hội'),
('B08', 'Toán, Sinh học, Tiếng Anh'),
('C00', 'Ngữ văn, Lịch sử, Địa lí'),
('C01', 'Ngữ văn, Toán, Vật lí'),
('C02', 'Ngữ văn, Toán, Hóa học'),
('C03', 'Ngữ văn, Toán, Lịch sử'),
('C04', 'Ngữ văn, Toán, Địa lí'),
('C05', 'Ngữ văn, Vật lí, Hóa học'),
('C06', 'Ngữ văn, Vật lí, Sinh học'),
('C07', 'Ngữ văn, Vật lí, Lịch sử'),
('C08', 'Ngữ văn, Hóa học, Sinh học'),
('C09', 'Ngữ văn, Vật lí, Địa lí'),
('C10', 'Ngữ văn, Hóa học, Lịch sử'),
('C12', 'Ngữ văn, Sinh học, Lịch sử'),
('C13', 'Ngữ văn, Sinh học, Địa lí'),
('C14', 'Ngữ văn, Toán, Giáo dục công dân'),
('C15', 'Ngữ văn, Toán, Khoa học xã hội'),
('C16', 'Ngữ văn, Vật lí, Giáo dục công dân'),
('C17', 'Ngữ văn, Hóa học, Giáo dục công dân'),
('C19', 'Ngữ văn, Lịch sử, Giáo dục công dân'),
('C20', 'Ngữ văn, Địa lí, Giáo dục công dân'),
('D01', 'Ngữ văn, Toán, Tiếng Anh'),
('D02', 'Ngữ văn, Toán, Tiếng Nga'),
('D03', 'Ngữ văn, Toán, Tiếng Pháp'),
('D04', 'Ngữ văn, Toán, Tiếng Trung'),
('D05', 'Ngữ văn, Toán, Tiếng Đức'),
('D06', 'Ngữ văn, Toán, Tiếng Nhật'),
('D07', 'Toán, Hóa học, Tiếng Anh'),
('D08', 'Toán, Sinh học, Tiếng Anh'),
('D09', 'Toán, Lịch sử, Tiếng Anh'),
('D10', 'Toán, Địa lí, Tiếng Anh'),
('D11', 'Ngữ văn, Vật lí, Tiếng Anh'),
('D12', 'Ngữ văn, Hóa học, Tiếng Anh'),
('D13', 'Ngữ văn, Sinh học, Tiếng Anh'),
('D14', 'Ngữ văn, Lịch sử, Tiếng Anh'),
('D15', 'Ngữ văn, Địa lí, Tiếng Anh'),
('D16', 'Toán, Địa lí, Tiếng Đức'),
('D17', 'Toán, Địa lí, Tiếng Nga'),
('D18', 'Toán, Địa lí, Tiếng Nhật'),
('D19', 'Toán, Địa lí, Tiếng Pháp'),
('D20', 'Toán, Địa lí, Tiếng Trung'),
('D21', 'Toán, Hóa học, Tiếng Đức'),
('D22', 'Toán, Hóa học, Tiếng Nga'),
('D23', 'Toán, Hóa học, Tiếng Nhật'),
('D24', 'Toán, Hóa học, Tiếng Pháp'),
('D25', 'Toán, Hóa học, Tiếng Trung'),
('D26', 'Toán, Vật lí, Tiếng Đức'),
('D27', 'Toán, Vật lí, Tiếng Nga'),
('D28', 'Toán, Vật lí, Tiếng Nhật'),
('D29', 'Toán, Vật lí, Tiếng Pháp'),
('D30', 'Toán, Vật lí, Tiếng Trung'),
('D31', 'Toán, Sinh học, Tiếng Đức'),
('D32', 'Toán, Sinh học, Tiếng Nga'),
('D33', 'Toán, Sinh học, Tiếng Nhật'),
('D34', 'Toán, Sinh học, Tiếng Pháp'),
('D35', 'Toán, Sinh học, Tiếng Trung'),
('D41', 'Ngữ văn, Địa lí, Tiếng Đức'),
('D42', 'Ngữ văn, Địa lí, Tiếng Nga'),
('D43', 'Ngữ văn, Địa lí, Tiếng Nhật'),
('D44', 'Ngữ văn, Địa lí, Tiếng Pháp'),
('D45', 'Ngữ văn, Địa lí, Tiếng Trung'),
('D52', 'Ngữ văn, Vật lí, Tiếng Nga'),
('D54', 'Ngữ văn, Vật lí, Tiếng Pháp'),
('D55', 'Ngữ văn, Vật lí, Tiếng Trung'),
('D61', 'Ngữ văn, Lịch sử, Tiếng Đức'),
('D62', 'Ngữ văn, Lịch sử, Tiếng Nga'),
('D63', 'Ngữ văn, Lịch sử, Tiếng Nhật'),
('D64', 'Ngữ văn, Lịch sử, Tiếng Pháp'),
('D65', 'Ngữ văn, Lịch sử, Tiếng Trung'),
('D66', 'Ngữ văn, Giáo dục công dân, Tiếng Anh'),
('D68', 'Ngữ văn, Giáo dục công dân, Tiếng Nga'),
('D69', 'Ngữ văn, Giáo dục công dân, Tiếng Nhật'),
('D70', 'Ngữ văn, Giáo dục công dân, Tiếng Pháp'),
('D72', 'Ngữ văn, Khoa học tự nhiên, Tiếng Anh'),
('D73', 'Ngữ văn, Khoa học tự nhiên, Tiếng Đức'),
('D74', 'Ngữ văn, Khoa học tự nhiên, Tiếng Nga'),
('D75', 'Ngữ văn, Khoa học tự nhiên, Tiếng Nhật'),
('D76', 'Ngữ văn, Khoa học tự nhiên, Tiếng Pháp'),
('D77', 'Ngữ văn, Khoa học tự nhiên, Tiếng Trung'),
('D78', 'Ngữ văn, Khoa học xã hội, Tiếng Anh'),
('D79', 'Ngữ văn, Khoa học xã hội, Tiếng Đức'),
('D80', 'Ngữ văn, Khoa học xã hội, Tiếng Nga'),
('D81', 'Ngữ văn, Khoa học xã hội, Tiếng Nhật'),
('D82', 'Ngữ văn, Khoa học xã hội, Tiếng Pháp'),
('D83', 'Ngữ văn, Khoa học xã hội, Tiếng Trung'),
('D84', 'Toán, Giáo dục công dân, Tiếng Anh'),
('D85', 'Toán, Giáo dục công dân, Tiếng Đức'),
('D86', 'Toán, Giáo dục công dân, Tiếng Nga'),
('D87', 'Toán, Giáo dục công dân, Tiếng Pháp'),
('D88', 'Toán, Giáo dục công dân, Tiếng Nhật'),
('D90', 'Toán, Khoa học tự nhiên, Tiếng Anh'),
('D91', 'Toán, Khoa học tự nhiên, Tiếng Pháp'),
('D92', 'Toán, Khoa học tự nhiên, Tiếng Đức'),
('D93', 'Toán, Khoa học tự nhiên, Tiếng Nga'),
('D94', 'Toán, Khoa học tự nhiên, Tiếng Nhật'),
('D95', 'Toán, Khoa học tự nhiên, Tiếng Trung'),
('D96', 'Toán, Khoa học xã hội, Tiếng Anh'),
('D97', 'Toán, Khoa học xã hội, Tiếng Pháp'),
('D98', 'Toán, Khoa học xã hội, Tiếng Đức'),
('D99', 'Toán, Khoa học xã hội, Tiếng Nga'),
('H00', 'Ngữ văn, Vẽ Nghệ thuật 1, Vẽ Nghệ thuật 2'),
('H01', 'Toán, Ngữ văn, Vẽ'),
('H02', 'Toán, Vẽ Hình họa mỹ thuật, Vẽ Trang trí màu'),
('H03', 'Toán, Khoa học tự nhiên, Vẽ Năng khiếu'),
('H04', 'Toán, Tiếng Anh, Vẽ Năng khiếu'),
('H05', 'Ngữ văn, Khoa học xã hội, Vẽ Năng khiếu'),
('H06', 'Ngữ văn, Tiếng Anh, Vẽ mỹ thuật'),
('H07', 'Toán, Hình họa, Trang trí'),
('H08', 'Ngữ văn, Lịch sử, Vẽ mỹ thuật'),
('K01', 'Toán, Tiếng Anh, Tin học'),
('M00', 'Ngữ văn, Toán, Đọc diễn cảm, Hát'),
('M01', 'Ngữ văn, Lịch sử, Năng khiếu'),
('M02', 'Toán, Năng khiếu 1, Năng khiếu 2'),
('M03', 'Ngữ văn, Năng khiếu 1, Năng khiếu 2'),
('M04', 'Toán, Đọc kể diễn cảm, Hát Múa'),
('M09', 'Toán, NK Mầm non 1 (Kể chuyện), NK Mầm non 2 (Hát)'),
('M10', 'Toán, Tiếng Anh, Năng khiếu 1'),
('M11', 'Ngữ văn, Năng khiếu báo chí, Tiếng Anh'),
('M13', 'Toán, Sinh học, Năng khiếu'),
('M14', 'Ngữ văn, Năng khiếu báo chí, Toán'),
('M15', 'Ngữ văn, Năng khiếu báo chí, Tiếng Anh'),
('M16', 'Ngữ văn, Năng khiếu báo chí, Vật lí'),
('M17', 'Ngữ văn, Năng khiếu báo chí, Lịch sử'),
('M18', 'Ngữ văn, Năng khiếu Ảnh báo chí, Toán'),
('M19', 'Ngữ văn, Năng khiếu Ảnh báo chí, Tiếng Anh'),
('M20', 'Ngữ văn, Năng khiếu Ảnh báo chí, Vật lí'),
('M21', 'Ngữ văn, Năng khiếu Ảnh báo chí, Lịch sử'),
('M22', 'Ngữ văn, Năng khiếu quay phim truyền hình, Toán'),
('M23', 'Ngữ văn, Năng khiếu quay phim truyền hình, Tiếng Anh'),
('M24', 'Ngữ văn, Năng khiếu quay phim truyền hình, Vật lí'),
('M25', 'Ngữ văn, Năng khiếu quay phim truyền hình, Lịch sử'),
('N00', 'Ngữ văn, Năng khiếu Âm nhạc 1, Năng khiếu Âm nhạc 2'),
('N01', 'Ngữ văn, Xướng âm, Biểu diễn nghệ thuật'),
('N02', 'Ngữ văn, Ký xướng âm, Hát hoặc Nhạc cụ'),
('N03', 'Ngữ văn, Ghi âm xướng âm, Chuyên môn'),
('N04', 'Ngữ văn, Năng khiếu thuyết trình, Năng khiếu'),
('N05', 'Ngữ văn, Xây dựng kịch bản sự kiện, Năng khiếu'),
('N06', 'Ngữ văn, Ghi âm xướng âm, Chuyên môn'),
('N07', 'Ngữ văn, Ghi âm xướng âm, Chuyên môn'),
('N08', 'Ngữ văn, Hòa thanh, Phát triển chủ đề và phổ thơ'),
('N09', 'Ngữ văn, Hòa thanh, Chỉ huy tại chỗ'),
('R00', 'Ngữ văn, Lịch sử, Năng khiếu báo chí'),
('R01', 'Ngữ văn, Địa lý, Năng khiếu Biểu diễn nghệ thuật'),
('R02', 'Ngữ văn, Toán, Năng khiếu Biểu diễn nghệ thuật'),
('R03', 'Ngữ văn, Tiếng Anh, Năng khiếu Biểu diễn nghệ thuật'),
('R04', 'Ngữ văn, Năng khiếu Biểu diễn, Năng khiếu Văn hóa nghệ thuật'),
('R05', 'Ngữ văn, Tiếng Anh, Năng khiếu kiến thức truyền thông'),
('S00', 'Ngữ văn, Năng khiếu SKĐA 1, Năng khiếu SKĐA 2'),
('S01', 'Toán, Năng khiếu 1, Năng khiếu 2'),
('T00', 'Toán, Sinh học, Năng khiếu TDTT'),
('T01', 'Toán, Ngữ văn, Năng khiếu TDTT'),
('T02', 'Ngữ văn, Sinh học, Năng khiếu TDTT'),
('T03', 'Ngữ văn, Địa lí, Năng khiếu TDTT'),
('T04', 'Toán, Vật lí, Năng khiếu TDTT'),
('T05', 'Ngữ văn, Giáo dục công dân, Năng khiếu'),
('V00', 'Toán, Vật lí, Vẽ Hình họa mỹ thuật'),
('V01', 'Toán, Ngữ văn, Vẽ Hình họa mỹ thuật'),
('V02', 'Vẽ mỹ thuật, Toán, Tiếng Anh'),
('V03', 'Vẽ mỹ thuật, Toán, Hóa học'),
('V05', 'Ngữ văn, Vật lí, Vẽ mỹ thuật'),
('V06', 'Toán, Địa lí, Vẽ mỹ thuật'),
('V07', 'Toán, Tiếng Đức, Vẽ mỹ thuật'),
('V08', 'Toán, Tiếng Nga, Vẽ mỹ thuật'),
('V09', 'Toán, Tiếng Nhật, Vẽ mỹ thuật'),
('V10', 'Toán, Tiếng Pháp, Vẽ mỹ thuật'),
('V11', 'Toán, Tiếng Trung, Vẽ mỹ thuật'),
('X06', 'Toán, Tin học, Tiếng Anh'),
('X26', 'Toán, Tin học, Vật lí')
ON CONFLICT (combination_code) DO NOTHING;

-- 3. CHI TIẾT MÔN THÀNH PHẦN TRONG TỔ HỢP (574 liên kết)
INSERT INTO combination_subjects (combination_code, subject_code) VALUES
('A00', 'TOAN'),
('A00', 'LY'),
('A00', 'HOA'),
('A01', 'TOAN'),
('A01', 'LY'),
('A01', 'ANH'),
('A02', 'TOAN'),
('A02', 'LY'),
('A02', 'SINH'),
('A03', 'TOAN'),
('A03', 'LY'),
('A03', 'SU'),
('A04', 'TOAN'),
('A04', 'LY'),
('A04', 'DIA'),
('A05', 'TOAN'),
('A05', 'HOA'),
('A05', 'SU'),
('A06', 'TOAN'),
('A06', 'HOA'),
('A06', 'DIA'),
('A07', 'TOAN'),
('A07', 'SU'),
('A07', 'DIA'),
('A08', 'TOAN'),
('A08', 'SU'),
('A08', 'GDCD_KTPL'),
('A09', 'TOAN'),
('A09', 'DIA'),
('A09', 'GDCD_KTPL'),
('A10', 'TOAN'),
('A10', 'LY'),
('A10', 'GDCD_KTPL'),
('A11', 'TOAN'),
('A11', 'HOA'),
('A11', 'GDCD_KTPL'),
('A12', 'TOAN'),
('A12', 'KHTN'),
('A12', 'KHXH'),
('A14', 'TOAN'),
('A14', 'KHTN'),
('A14', 'DIA'),
('A15', 'TOAN'),
('A15', 'KHTN'),
('A15', 'GDCD_KTPL'),
('A16', 'TOAN'),
('A16', 'KHTN'),
('A16', 'VAN'),
('A17', 'TOAN'),
('A17', 'LY'),
('A17', 'KHXH'),
('A18', 'TOAN'),
('A18', 'HOA'),
('A18', 'KHXH'),
('B00', 'TOAN'),
('B00', 'HOA'),
('B00', 'SINH'),
('B01', 'TOAN'),
('B01', 'SINH'),
('B01', 'SU'),
('B02', 'TOAN'),
('B02', 'SINH'),
('B02', 'DIA'),
('B03', 'TOAN'),
('B03', 'SINH'),
('B03', 'VAN'),
('B04', 'TOAN'),
('B04', 'SINH'),
('B04', 'GDCD_KTPL'),
('B05', 'TOAN'),
('B05', 'SINH'),
('B05', 'KHXH'),
('B08', 'TOAN'),
('B08', 'SINH'),
('B08', 'ANH'),
('C00', 'VAN'),
('C00', 'SU'),
('C00', 'DIA'),
('C01', 'VAN'),
('C01', 'TOAN'),
('C01', 'LY'),
('C02', 'VAN'),
('C02', 'TOAN'),
('C02', 'HOA'),
('C03', 'VAN'),
('C03', 'TOAN'),
('C03', 'SU'),
('C04', 'VAN'),
('C04', 'TOAN'),
('C04', 'DIA'),
('C05', 'VAN'),
('C05', 'LY'),
('C05', 'HOA'),
('C06', 'VAN'),
('C06', 'LY'),
('C06', 'SINH'),
('C07', 'VAN'),
('C07', 'LY'),
('C07', 'SU'),
('C08', 'VAN'),
('C08', 'HOA'),
('C08', 'SINH'),
('C09', 'VAN'),
('C09', 'LY'),
('C09', 'DIA'),
('C10', 'VAN'),
('C10', 'HOA'),
('C10', 'SU'),
('C12', 'VAN'),
('C12', 'SINH'),
('C12', 'SU'),
('C13', 'VAN'),
('C13', 'SINH'),
('C13', 'DIA'),
('C14', 'VAN'),
('C14', 'TOAN'),
('C14', 'GDCD_KTPL'),
('C15', 'VAN'),
('C15', 'TOAN'),
('C15', 'KHXH'),
('C16', 'VAN'),
('C16', 'LY'),
('C16', 'GDCD_KTPL'),
('C17', 'VAN'),
('C17', 'HOA'),
('C17', 'GDCD_KTPL'),
('C19', 'VAN'),
('C19', 'SU'),
('C19', 'GDCD_KTPL'),
('C20', 'VAN'),
('C20', 'DIA'),
('C20', 'GDCD_KTPL'),
('D01', 'VAN'),
('D01', 'TOAN'),
('D01', 'ANH'),
('D02', 'VAN'),
('D02', 'TOAN'),
('D02', 'NGA'),
('D03', 'VAN'),
('D03', 'TOAN'),
('D03', 'PHAP'),
('D04', 'VAN'),
('D04', 'TOAN'),
('D04', 'TRUNG'),
('D05', 'VAN'),
('D05', 'TOAN'),
('D05', 'DUC'),
('D06', 'VAN'),
('D06', 'TOAN'),
('D06', 'NHAT'),
('D07', 'TOAN'),
('D07', 'HOA'),
('D07', 'ANH'),
('D08', 'TOAN'),
('D08', 'SINH'),
('D08', 'ANH'),
('D09', 'TOAN'),
('D09', 'SU'),
('D09', 'ANH'),
('D10', 'TOAN'),
('D10', 'DIA'),
('D10', 'ANH'),
('D11', 'VAN'),
('D11', 'LY'),
('D11', 'ANH'),
('D12', 'VAN'),
('D12', 'HOA'),
('D12', 'ANH'),
('D13', 'VAN'),
('D13', 'SINH'),
('D13', 'ANH'),
('D14', 'VAN'),
('D14', 'SU'),
('D14', 'ANH'),
('D15', 'VAN'),
('D15', 'DIA'),
('D15', 'ANH'),
('D16', 'TOAN'),
('D16', 'DIA'),
('D16', 'DUC'),
('D17', 'TOAN'),
('D17', 'DIA'),
('D17', 'NGA'),
('D18', 'TOAN'),
('D18', 'DIA'),
('D18', 'NHAT'),
('D19', 'TOAN'),
('D19', 'DIA'),
('D19', 'PHAP'),
('D20', 'TOAN'),
('D20', 'DIA'),
('D20', 'TRUNG'),
('D21', 'TOAN'),
('D21', 'HOA'),
('D21', 'DUC'),
('D22', 'TOAN'),
('D22', 'HOA'),
('D22', 'NGA'),
('D23', 'TOAN'),
('D23', 'HOA'),
('D23', 'NHAT'),
('D24', 'TOAN'),
('D24', 'HOA'),
('D24', 'PHAP'),
('D25', 'TOAN'),
('D25', 'HOA'),
('D25', 'TRUNG'),
('D26', 'TOAN'),
('D26', 'LY'),
('D26', 'DUC'),
('D27', 'TOAN'),
('D27', 'LY'),
('D27', 'NGA'),
('D28', 'TOAN'),
('D28', 'LY'),
('D28', 'NHAT'),
('D29', 'TOAN'),
('D29', 'LY'),
('D29', 'PHAP'),
('D30', 'TOAN'),
('D30', 'LY'),
('D30', 'TRUNG'),
('D31', 'TOAN'),
('D31', 'SINH'),
('D31', 'DUC'),
('D32', 'TOAN'),
('D32', 'SINH'),
('D32', 'NGA'),
('D33', 'TOAN'),
('D33', 'SINH'),
('D33', 'NHAT'),
('D34', 'TOAN'),
('D34', 'SINH'),
('D34', 'PHAP'),
('D35', 'TOAN'),
('D35', 'SINH'),
('D35', 'TRUNG'),
('D41', 'VAN'),
('D41', 'DIA'),
('D41', 'DUC'),
('D42', 'VAN'),
('D42', 'DIA'),
('D42', 'NGA'),
('D43', 'VAN'),
('D43', 'DIA'),
('D43', 'NHAT'),
('D44', 'VAN'),
('D44', 'DIA'),
('D44', 'PHAP'),
('D45', 'VAN'),
('D45', 'DIA'),
('D45', 'TRUNG'),
('D52', 'VAN'),
('D52', 'LY'),
('D52', 'NGA'),
('D54', 'VAN'),
('D54', 'LY'),
('D54', 'PHAP'),
('D55', 'VAN'),
('D55', 'LY'),
('D55', 'TRUNG'),
('D61', 'VAN'),
('D61', 'SU'),
('D61', 'DUC'),
('D62', 'VAN'),
('D62', 'SU'),
('D62', 'NGA'),
('D63', 'VAN'),
('D63', 'SU'),
('D63', 'NHAT'),
('D64', 'VAN'),
('D64', 'SU'),
('D64', 'PHAP'),
('D65', 'VAN'),
('D65', 'SU'),
('D65', 'TRUNG'),
('D66', 'VAN'),
('D66', 'GDCD_KTPL'),
('D66', 'ANH'),
('D68', 'VAN'),
('D68', 'GDCD_KTPL'),
('D68', 'NGA'),
('D69', 'VAN'),
('D69', 'GDCD_KTPL'),
('D69', 'NHAT'),
('D70', 'VAN'),
('D70', 'GDCD_KTPL'),
('D70', 'PHAP'),
('D72', 'VAN'),
('D72', 'KHTN'),
('D72', 'ANH'),
('D73', 'VAN'),
('D73', 'KHTN'),
('D73', 'DUC'),
('D74', 'VAN'),
('D74', 'KHTN'),
('D74', 'NGA'),
('D75', 'VAN'),
('D75', 'KHTN'),
('D75', 'NHAT'),
('D76', 'VAN'),
('D76', 'KHTN'),
('D76', 'PHAP'),
('D77', 'VAN'),
('D77', 'KHTN'),
('D77', 'TRUNG'),
('D78', 'VAN'),
('D78', 'KHXH'),
('D78', 'ANH'),
('D79', 'VAN'),
('D79', 'KHXH'),
('D79', 'DUC'),
('D80', 'VAN'),
('D80', 'KHXH'),
('D80', 'NGA'),
('D81', 'VAN'),
('D81', 'KHXH'),
('D81', 'NHAT'),
('D82', 'VAN'),
('D82', 'KHXH'),
('D82', 'PHAP'),
('D83', 'VAN'),
('D83', 'KHXH'),
('D83', 'TRUNG'),
('D84', 'TOAN'),
('D84', 'GDCD_KTPL'),
('D84', 'ANH'),
('D85', 'TOAN'),
('D85', 'GDCD_KTPL'),
('D85', 'DUC'),
('D86', 'TOAN'),
('D86', 'GDCD_KTPL'),
('D86', 'NGA'),
('D87', 'TOAN'),
('D87', 'GDCD_KTPL'),
('D87', 'PHAP'),
('D88', 'TOAN'),
('D88', 'GDCD_KTPL'),
('D88', 'NHAT'),
('D90', 'TOAN'),
('D90', 'KHTN'),
('D90', 'ANH'),
('D91', 'TOAN'),
('D91', 'KHTN'),
('D91', 'PHAP'),
('D92', 'TOAN'),
('D92', 'KHTN'),
('D92', 'DUC'),
('D93', 'TOAN'),
('D93', 'KHTN'),
('D93', 'NGA'),
('D94', 'TOAN'),
('D94', 'KHTN'),
('D94', 'NHAT'),
('D95', 'TOAN'),
('D95', 'KHTN'),
('D95', 'TRUNG'),
('D96', 'TOAN'),
('D96', 'KHXH'),
('D96', 'ANH'),
('D97', 'TOAN'),
('D97', 'KHXH'),
('D97', 'PHAP'),
('D98', 'TOAN'),
('D98', 'KHXH'),
('D98', 'DUC'),
('D99', 'TOAN'),
('D99', 'KHXH'),
('D99', 'NGA'),
('H00', 'VAN'),
('H00', 'VE_NGHETHUAT_1'),
('H00', 'VE_NGHETHUAT_2'),
('H01', 'TOAN'),
('H01', 'VAN'),
('H01', 'VE'),
('H02', 'TOAN'),
('H02', 'VE_HINHHOA'),
('H02', 'VE_TRANGTRI_MAU'),
('H03', 'TOAN'),
('H03', 'KHTN'),
('H03', 'VE_NANGKHIEU'),
('H04', 'TOAN'),
('H04', 'ANH'),
('H04', 'VE_NANGKHIEU'),
('H05', 'VAN'),
('H05', 'KHXH'),
('H05', 'VE_NANGKHIEU'),
('H06', 'VAN'),
('H06', 'ANH'),
('H06', 'VE_MYTHUAT'),
('H07', 'TOAN'),
('H07', 'HINH_HOA'),
('H07', 'TRANG_TRI'),
('H08', 'VAN'),
('H08', 'SU'),
('H08', 'VE_MYTHUAT'),
('K01', 'TOAN'),
('K01', 'ANH'),
('K01', 'TIN'),
('M00', 'VAN'),
('M00', 'TOAN'),
('M00', 'DOC_DIENCAM'),
('M00', 'HAT'),
('M01', 'VAN'),
('M01', 'SU'),
('M01', 'NANG_KHIEU'),
('M02', 'TOAN'),
('M02', 'NANG_KHIEU_1'),
('M02', 'NANG_KHIEU_2'),
('M03', 'VAN'),
('M03', 'NANG_KHIEU_1'),
('M03', 'NANG_KHIEU_2'),
('M04', 'TOAN'),
('M04', 'DOC_DIENCAM'),
('M04', 'HAT_MUA'),
('M09', 'TOAN'),
('M09', 'NK_MAMNON_1'),
('M09', 'NK_MAMNON_2'),
('M10', 'TOAN'),
('M10', 'ANH'),
('M10', 'NANG_KHIEU_1'),
('M11', 'VAN'),
('M11', 'NK_BAOCHI'),
('M11', 'ANH'),
('M13', 'TOAN'),
('M13', 'SINH'),
('M13', 'NANG_KHIEU'),
('M14', 'VAN'),
('M14', 'NK_BAOCHI'),
('M14', 'TOAN'),
('M15', 'VAN'),
('M15', 'NK_BAOCHI'),
('M15', 'ANH'),
('M16', 'VAN'),
('M16', 'NK_BAOCHI'),
('M16', 'LY'),
('M17', 'VAN'),
('M17', 'NK_BAOCHI'),
('M17', 'SU'),
('M18', 'VAN'),
('M18', 'NK_ANH_BAOCHI'),
('M18', 'TOAN'),
('M19', 'VAN'),
('M19', 'NK_ANH_BAOCHI'),
('M19', 'ANH'),
('M20', 'VAN'),
('M20', 'NK_ANH_BAOCHI'),
('M20', 'LY'),
('M21', 'VAN'),
('M21', 'NK_ANH_BAOCHI'),
('M21', 'SU'),
('M22', 'VAN'),
('M22', 'NK_QUAYPHIM'),
('M22', 'TOAN'),
('M23', 'VAN'),
('M23', 'NK_QUAYPHIM'),
('M23', 'ANH'),
('M24', 'VAN'),
('M24', 'NK_QUAYPHIM'),
('M24', 'LY'),
('M25', 'VAN'),
('M25', 'NK_QUAYPHIM'),
('M25', 'SU'),
('N00', 'VAN'),
('N00', 'NK_AMNHAC_1'),
('N00', 'NK_AMNHAC_2'),
('N01', 'VAN'),
('N01', 'XUONG_AM'),
('N01', 'BIEUDIEN_NGHETHUAT'),
('N02', 'VAN'),
('N02', 'KY_XUONG_AM'),
('N02', 'HAT_NHACCU'),
('N03', 'VAN'),
('N03', 'GHI_AM_XUONG_AM'),
('N03', 'CHUYEN_MON_AMNHAC'),
('N04', 'VAN'),
('N04', 'NK_THUYETTRINH'),
('N04', 'NANG_KHIEU'),
('N05', 'VAN'),
('N05', 'NK_KICHBAN_SUKIEN'),
('N05', 'NANG_KHIEU'),
('N06', 'VAN'),
('N06', 'GHI_AM_XUONG_AM'),
('N06', 'CHUYEN_MON_AMNHAC'),
('N07', 'VAN'),
('N07', 'GHI_AM_XUONG_AM'),
('N07', 'CHUYEN_MON_AMNHAC'),
('N08', 'VAN'),
('N08', 'HOA_THANH'),
('N08', 'PHAT_TRIEN_CHU_DE'),
('N09', 'VAN'),
('N09', 'HOA_THANH'),
('N09', 'CHI_HUY_TAI_CHO'),
('R00', 'VAN'),
('R00', 'SU'),
('R00', 'NK_BAOCHI'),
('R01', 'VAN'),
('R01', 'DIA'),
('R01', 'BIEUDIEN_NGHETHUAT'),
('R02', 'VAN'),
('R02', 'TOAN'),
('R02', 'BIEUDIEN_NGHETHUAT'),
('R03', 'VAN'),
('R03', 'ANH'),
('R03', 'BIEUDIEN_NGHETHUAT'),
('R04', 'VAN'),
('R04', 'BIEUDIEN_NGHETHUAT'),
('R04', 'NK_VANHOA_NGHETHUAT'),
('R05', 'VAN'),
('R05', 'ANH'),
('R05', 'NK_KIENTHUC_TRUYENTHONG'),
('S00', 'VAN'),
('S00', 'NK_SKDA_1'),
('S00', 'NK_SKDA_2'),
('S01', 'TOAN'),
('S01', 'NANG_KHIEU_1'),
('S01', 'NANG_KHIEU_2'),
('T00', 'TOAN'),
('T00', 'SINH'),
('T00', 'NK_TDTT'),
('T01', 'TOAN'),
('T01', 'VAN'),
('T01', 'NK_TDTT'),
('T02', 'VAN'),
('T02', 'SINH'),
('T02', 'NK_TDTT'),
('T03', 'VAN'),
('T03', 'DIA'),
('T03', 'NK_TDTT'),
('T04', 'TOAN'),
('T04', 'LY'),
('T04', 'NK_TDTT'),
('T05', 'VAN'),
('T05', 'GDCD_KTPL'),
('T05', 'NANG_KHIEU'),
('V00', 'TOAN'),
('V00', 'LY'),
('V00', 'VE_HINHHOA'),
('V01', 'TOAN'),
('V01', 'VAN'),
('V01', 'VE_HINHHOA'),
('V02', 'VE_MYTHUAT'),
('V02', 'TOAN'),
('V02', 'ANH'),
('V03', 'VE_MYTHUAT'),
('V03', 'TOAN'),
('V03', 'HOA'),
('V05', 'VAN'),
('V05', 'LY'),
('V05', 'VE_MYTHUAT'),
('V06', 'TOAN'),
('V06', 'DIA'),
('V06', 'VE_MYTHUAT'),
('V07', 'TOAN'),
('V07', 'DUC'),
('V07', 'VE_MYTHUAT'),
('V08', 'TOAN'),
('V08', 'NGA'),
('V08', 'VE_MYTHUAT'),
('V09', 'TOAN'),
('V09', 'NHAT'),
('V09', 'VE_MYTHUAT'),
('V10', 'TOAN'),
('V10', 'PHAP'),
('V10', 'VE_MYTHUAT'),
('V11', 'TOAN'),
('V11', 'TRUNG'),
('V11', 'VE_MYTHUAT'),
('X06', 'TOAN'),
('X06', 'TIN'),
('X06', 'ANH'),
('X26', 'TOAN'),
('X26', 'TIN'),
('X26', 'LY')
ON CONFLICT DO NOTHING;

-- 4. PHƯƠNG THỨC TUYỂN SINH CHUẨN CỦA BỘ GD&ĐT
INSERT INTO admission_methods (method_id, method_code, method_name, target_group) VALUES
('PT100', '100', 'Xét kết quả thi tốt nghiệp THPT', 'THPT'),
('PT200', '200', 'Xét kết quả học tập cấp THPT (học bạ)', 'Học bạ'),
('PT301', '301', 'Xét tuyển thẳng theo quy chế của Bộ GD&ĐT', 'Tuyển thẳng'),
('PT402', '402', 'Xét tuyển kết quả thi đánh giá năng lực, đánh giá tư duy', 'ĐGNL/ĐGTD'),
('PT_KETHOP', '500', 'Xét tuyển kết hợp chứng chỉ ngoại ngữ và kết quả thi/học bạ', 'Kết hợp CCQT')
ON CONFLICT (method_id) DO NOTHING;

-- 5. TÀI KHOẢN QUẢN TRỊ VIÊN MẶC ĐỊNH (Default System Admin Account)
-- Email: admin@admissionkg.edu.vn | Mật khẩu: admin123
INSERT INTO users (email, full_name, password, role) VALUES
('admin@admissionkg.edu.vn', 'Quản trị viên Hệ thống', '$2a$10$I50HYlmm7dk19y0KX0wzVeQmwfDvhCBh/Z/qNfmFdO23uTg9dUb1C', 'ROLE_ADMIN')
ON CONFLICT (email) DO UPDATE 
SET role = 'ROLE_ADMIN', 
    full_name = EXCLUDED.full_name, 
    password = EXCLUDED.password;
